#!/usr/bin/env python3
"""
Apply Cuts Executor
====================
Reads a cut_spec.json file, extracts each keep segment using ffmpeg,
then concatenates them into a single output file (lossless, no re-encoding).

Usage:
    python executors/video/apply_cuts.py <cut_spec_json> <output_file> [--temp-dir <dir>]
    python executors/video/apply_cuts.py --help

Arguments:
    cut_spec_json   Path to the cut spec JSON file (generated by Claude's analysis)
    output_file     Path for the final concatenated output video

Options:
    --temp-dir DIR  Directory for intermediate segment files (default: workspace/temp)

cut_spec.json format:
    {
      "source": "workspace/input/video.mp4",
      "keep_segments": [
        {"start": "00:00:00", "end": "00:01:23", "note": "successful take 1"},
        {"start": "00:02:10", "end": "00:05:44", "note": "successful take 2"}
      ],
      "removed_segments": [
        {"start": "00:01:23", "end": "00:02:10", "reason": "retake — repeated intro"}
      ]
    }

Output:
    Prints a JSON result object to stdout.
    Exits 0 on success, 1 on failure.

Notes:
    - Uses ffmpeg stream copy (-c copy) for lossless, near-instant processing
    - Intermediate segment files are written to workspace/temp/ and cleaned up after
    - If stream copy fails (codec mismatch), re-encodes with libx264/aac as fallback
"""

import sys
import json
import subprocess
import os
from pathlib import Path

# Import trim function from sibling module
sys.path.insert(0, str(Path(__file__).parent))
from trim import trim_video, parse_timestamp

# Seconds added to each segment's end timestamp to let speech trail off naturally
END_PADDING_SECONDS = 0.1

# Seconds subtracted from each segment's start timestamp to prevent clipping the
# first phoneme of a word. Whisper marks `start` at the exact moment speech begins
# with no pre-roll, so without this buffer the initial consonant gets cut off.
START_PADDING_SECONDS = 0.1


def seconds_to_hms(total_seconds: float) -> str:
    """Convert float seconds to HH:MM:SS string."""
    h = int(total_seconds // 3600)
    m = int((total_seconds % 3600) // 60)
    s = total_seconds % 60
    return f"{h:02d}:{m:02d}:{s:06.3f}"


def concat_segments(segment_files: list, output_file: str, temp_dir: Path | None = None) -> dict:
    """
    Concatenate a list of video files using ffmpeg concat demuxer (lossless).
    Falls back to re-encode if stream copy fails.
    """
    if temp_dir is None:
        temp_dir = Path("workspace/temp")
    # Write a concat list file
    concat_list_path = temp_dir / "_concat_list.txt"
    concat_list_path.parent.mkdir(parents=True, exist_ok=True)

    with open(concat_list_path, 'w') as f:
        for seg_file in segment_files:
            # ffmpeg concat demuxer requires absolute or correctly relative paths
            abs_path = Path(seg_file).resolve()
            f.write(f"file '{abs_path}'\n")

    Path(output_file).parent.mkdir(parents=True, exist_ok=True)

    cmd = [
        'ffmpeg',
        '-f', 'concat',
        '-safe', '0',
        '-i', str(concat_list_path),
        '-c', 'copy',
        '-y',
        output_file
    ]
    cmd_str = ' '.join(f'"{a}"' if ' ' in a else a for a in cmd)

    result = subprocess.run(cmd, capture_output=True, text=True, timeout=600)

    # Clean up concat list
    try:
        concat_list_path.unlink()
    except OSError:
        pass

    if result.returncode != 0:
        # Fallback: try re-encoding
        print("Stream copy concat failed, trying re-encode fallback...", file=sys.stderr)
        cmd_reencode = [
            'ffmpeg',
            '-f', 'concat',
            '-safe', '0',
            '-i', str(concat_list_path.with_suffix('.txt')),
            '-c:v', 'libx264',
            '-c:a', 'aac',
            '-y',
            output_file
        ]
        # Re-write list for fallback
        with open(concat_list_path, 'w') as f:
            for seg_file in segment_files:
                abs_path = Path(seg_file).resolve()
                f.write(f"file '{abs_path}'\n")

        result2 = subprocess.run(cmd_reencode, capture_output=True, text=True, timeout=600)
        try:
            concat_list_path.unlink()
        except OSError:
            pass

        if result2.returncode != 0:
            return {
                "status": "error",
                "error": "Concat failed with both stream copy and re-encode",
                "stream_copy_stderr": result.stderr,
                "reencode_stderr": result2.stderr,
                "ffmpeg_command": cmd_str
            }

    return {"status": "success", "ffmpeg_command": cmd_str}


def apply_cuts(cut_spec_path: str, output_file: str, temp_dir: str = "workspace/temp") -> dict:
    """
    Main function: extract all keep_segments then concatenate into output_file.
    """
    # Load cut spec
    if not Path(cut_spec_path).exists():
        return {"status": "error", "error": f"Cut spec not found: {cut_spec_path}"}

    with open(cut_spec_path) as f:
        spec = json.load(f)

    source = spec.get("source", "")
    keep_segments = spec.get("keep_segments", [])
    removed_segments = spec.get("removed_segments", [])

    if not Path(source).exists():
        return {"status": "error", "error": f"Source file not found: {source}"}

    if not keep_segments:
        return {"status": "error", "error": "No keep_segments defined in cut spec"}

    # Calculate total duration of source (for reporting)
    source_duration = 0.0
    try:
        cmd = ['ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_format', source]
        probe = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        if probe.returncode == 0:
            info = json.loads(probe.stdout)
            source_duration = float(info.get("format", {}).get("duration", 0.0))
    except Exception:
        pass

    # Extract each segment to a temp file
    temp_dir = Path(temp_dir)
    temp_dir.mkdir(parents=True, exist_ok=True)
    segment_files = []
    total_kept_duration = 0.0

    print(f"Extracting {len(keep_segments)} segment(s)...", file=sys.stderr)

    for i, seg in enumerate(keep_segments):
        start = seg["start"]
        end = seg["end"]
        note = seg.get("note", "")
        temp_output = str(temp_dir / f"_seg_{i:03d}{Path(source).suffix}")

        # Apply start padding so the first phoneme is never clipped.
        # Whisper timestamps mark exactly when speech begins — no pre-roll.
        # Clamp to 0 so we never seek before the beginning of the file.
        try:
            start = seconds_to_hms(max(0.0, parse_timestamp(start) - START_PADDING_SECONDS))
        except ValueError:
            pass

        # Apply end padding so speech trails off naturally before the cut
        try:
            end = seconds_to_hms(parse_timestamp(end) + END_PADDING_SECONDS)
        except ValueError:
            pass

        print(f"  [{i+1}/{len(keep_segments)}] {start} → {end}  ({note})", file=sys.stderr)

        result = trim_video(source, start, end, temp_output, re_encode=True)
        if result["status"] != "success":
            # Clean up any already-extracted segments
            for f in segment_files:
                try:
                    Path(f).unlink()
                except OSError:
                    pass
            return {
                "status": "error",
                "error": f"Failed to extract segment {i+1}: {result.get('error')}",
                "segment": seg,
                "trim_result": result
            }

        segment_files.append(temp_output)
        try:
            kept_start = parse_timestamp(start)
            kept_end = parse_timestamp(end)
            total_kept_duration += (kept_end - kept_start)
        except ValueError:
            pass

    # Concatenate all segments
    if len(segment_files) == 1:
        # Only one segment — just move/copy it directly
        import shutil
        Path(output_file).parent.mkdir(parents=True, exist_ok=True)
        shutil.move(segment_files[0], output_file)
        concat_result = {"status": "success", "ffmpeg_command": "single segment — no concat needed"}
    else:
        print(f"Concatenating {len(segment_files)} segments...", file=sys.stderr)
        concat_result = concat_segments(segment_files, output_file, temp_dir)

        # Clean up temp segment files
        for f in segment_files:
            try:
                Path(f).unlink()
            except OSError:
                pass

    if concat_result["status"] != "success":
        return concat_result

    # Gather final output stats
    output_path = Path(output_file)
    file_size = output_path.stat().st_size if output_path.exists() else 0
    duration_removed = source_duration - total_kept_duration if source_duration > 0 else 0

    print(f"\nDone. Output: {output_file}", file=sys.stderr)
    print(f"  Source duration:   {seconds_to_hms(source_duration)}", file=sys.stderr)
    print(f"  Kept duration:     {seconds_to_hms(total_kept_duration)}", file=sys.stderr)
    print(f"  Removed duration:  {seconds_to_hms(max(0, duration_removed))}", file=sys.stderr)
    print(f"  Segments removed:  {len(removed_segments)}", file=sys.stderr)

    return {
        "status": "success",
        "output_file": str(output_path.resolve()),
        "source_file": str(Path(source).resolve()),
        "source_duration_seconds": round(source_duration, 3),
        "output_duration_seconds": round(total_kept_duration, 3),
        "removed_duration_seconds": round(max(0, duration_removed), 3),
        "segments_kept": len(keep_segments),
        "segments_removed": len(removed_segments),
        "file_size_bytes": file_size,
        "file_size_mb": round(file_size / (1024 * 1024), 2)
    }


def main():
    args = sys.argv[1:]

    if not args or args[0] in ('-h', '--help'):
        print(__doc__)
        sys.exit(0)

    # Parse --temp-dir option
    temp_dir = "workspace/temp"
    positional = []
    i = 0
    while i < len(args):
        if args[i] == '--temp-dir' and i + 1 < len(args):
            temp_dir = args[i + 1]
            i += 2
        else:
            positional.append(args[i])
            i += 1

    if len(positional) < 2:
        print(json.dumps({
            "status": "error",
            "error": "Usage: apply_cuts.py <cut_spec_json> <output_file> [--temp-dir <dir>]"
        }, indent=2))
        sys.exit(1)

    cut_spec_path = positional[0]
    output_file = positional[1]

    result = apply_cuts(cut_spec_path, output_file, temp_dir)
    print(json.dumps(result, indent=2))
    sys.exit(0 if result['status'] == 'success' else 1)


if __name__ == '__main__':
    main()
