#!/usr/bin/env python3
"""
Apply Cuts Executor
====================
Reads a cut_spec.json file, extracts each keep segment using ffmpeg,
then outputs them according to the selected mode.

Usage:
    python executors/video/apply_cuts.py <cut_spec_json> <output> [--temp-dir <dir>] [--mode <mode>]
    python executors/video/apply_cuts.py <cut_spec_json> <clips_dir> --mode both --joined-output <joined_file>
    python executors/video/apply_cuts.py --help

Arguments:
    cut_spec_json   Path to the cut spec JSON file (generated by Claude's analysis)
    output          For 'joined' mode: output file path
                    For 'separate'/'project'/'both' mode: output directory path

Options:
    --temp-dir DIR          Directory for intermediate segment files (default: workspace/temp)
    --mode MODE             Output mode: joined (default), separate, project, both
    --joined-output PATH    Joined output file path (required when mode is 'both')

Modes:
    joined      Concatenate all segments into a single output file (default)
    separate    Save each segment as a separate numbered clip file
    project     Save separate clips + generate FCP7 XML project for Premiere Pro import
    both        Extract segments once, produce joined file + project clips/XML (most efficient)

cut_spec.json format:
    {
      "source": "workspace/input/video.mp4",
      "keep_segments": [
        {"start": "00:00:00", "end": "00:01:23", "note": "successful take 1"},
        {"start": "00:02:10", "end": "00:05:44", "note": "successful take 2"}
      ],
      "removed_segments": [
        {"start": "00:01:23", "end": "00:02:10", "reason": "retake — repeated intro"}
      ]
    }

Output:
    Prints a JSON result object to stdout.
    Exits 0 on success, 1 on failure.

Notes:
    - Uses ffmpeg stream copy (-c copy) for lossless, near-instant processing
    - Intermediate segment files are written to workspace/temp/ and cleaned up after
    - If stream copy fails (codec mismatch), re-encodes with libx264/aac as fallback
"""

import sys
import json
import time
import shutil
import subprocess
import os
import xml.etree.ElementTree as ET
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Optional

# Import trim function from sibling module
sys.path.insert(0, str(Path(__file__).parent))
from trim import trim_video, parse_timestamp

# Seconds added to each segment's end timestamp to let speech trail off naturally
END_PADDING_SECONDS = 0.1

# Seconds subtracted from each segment's start timestamp to prevent clipping the
# first phoneme of a word. Whisper marks `start` at the exact moment speech begins
# with no pre-roll, so without this buffer the initial consonant gets cut off.
START_PADDING_SECONDS = 0.1

# Maximum gap (seconds) between two consecutive keep_segments for them to be
# merged into a single clip.  Segments whose end/start timestamps are within
# this tolerance are treated as contiguous — prevents tiny fragment clips.
MERGE_GAP_THRESHOLD = 0.05

# Gaps shorter than this between consecutive keep_segments are bridged
# automatically.  Whisper often fails to transcribe brief utterances
# (e.g. "but wait", "ok so", transition phrases) that fall in short gaps.
# Bridging preserves natural flow instead of cutting mid-speech.
# Set higher than MERGE_GAP_THRESHOLD — this catches *meaningful* gaps that
# are still too short to be intentional removed content (retakes are typically
# several seconds long).
MIN_INTER_SEGMENT_GAP = 1.0


def merge_adjacent_segments(segments: list, threshold: float = MERGE_GAP_THRESHOLD) -> list:
    """Merge consecutive keep_segments that are contiguous (or nearly so).

    When the cut spec splits a single logical take into multiple entries
    (e.g. because Whisper produced fine-grained word-level boundaries),
    they end up as tiny fragment clips.  This function fuses any pair of
    adjacent segments whose gap is within *threshold* seconds, producing
    fewer, more meaningful clips.
    """
    if not segments:
        return segments

    merged = [dict(segments[0])]
    for seg in segments[1:]:
        prev = merged[-1]
        prev_end = parse_timestamp(prev["end"])
        curr_start = parse_timestamp(seg["start"])
        if curr_start - prev_end <= threshold:
            # Extend previous segment to cover the current one
            prev["end"] = seg["end"]
            # Combine notes when they differ
            if seg.get("note") and seg["note"] != prev.get("note"):
                prev["note"] = prev.get("note", "") + " | " + seg["note"]
        else:
            merged.append(dict(seg))
    return merged


def bridge_short_gaps(segments: list, threshold: float = MIN_INTER_SEGMENT_GAP) -> list:
    """Bridge gaps shorter than *threshold* between consecutive segments.

    Short gaps between keep_segments often contain brief speech that Whisper
    didn't transcribe (e.g. transition phrases like "but wait, that's not
    all").  Bridging extends the previous segment's end to cover the gap and
    the next segment, preserving natural speech flow.

    This runs AFTER merge_adjacent_segments — it's a second, coarser pass.
    """
    if len(segments) < 2:
        return segments

    bridged = [dict(segments[0])]
    for seg in segments[1:]:
        prev = bridged[-1]
        prev_end = parse_timestamp(prev["end"])
        curr_start = parse_timestamp(seg["start"])
        gap = curr_start - prev_end
        if 0 < gap < threshold:
            # Bridge: extend previous segment to cover the gap
            prev["end"] = seg["end"]
            if seg.get("note") and seg["note"] != prev.get("note"):
                prev["note"] = prev.get("note", "") + " | " + seg["note"]
        else:
            bridged.append(dict(seg))
    return bridged


def seconds_to_hms(total_seconds: float) -> str:
    """Convert float seconds to HH:MM:SS string."""
    h = int(total_seconds // 3600)
    m = int((total_seconds % 3600) // 60)
    s = total_seconds % 60
    return f"{h:02d}:{m:02d}:{s:06.3f}"


def concat_segments(segment_files: list, output_file: str, temp_dir: Optional[Path] = None) -> dict:
    """
    Concatenate a list of video files using ffmpeg concat demuxer (lossless).
    Falls back to re-encode if stream copy fails.
    """
    if temp_dir is None:
        temp_dir = Path("workspace/temp")
    # Write a concat list file
    concat_list_path = temp_dir / "_concat_list.txt"
    concat_list_path.parent.mkdir(parents=True, exist_ok=True)

    with open(concat_list_path, 'w') as f:
        for seg_file in segment_files:
            # ffmpeg concat demuxer requires absolute or correctly relative paths
            abs_path = Path(seg_file).resolve()
            f.write(f"file '{abs_path}'\n")

    Path(output_file).parent.mkdir(parents=True, exist_ok=True)

    cmd = [
        'ffmpeg',
        '-f', 'concat',
        '-safe', '0',
        '-i', str(concat_list_path),
        '-c', 'copy',
        '-y',
        output_file
    ]
    cmd_str = ' '.join(f'"{a}"' if ' ' in a else a for a in cmd)

    result = subprocess.run(cmd, capture_output=True, text=True, timeout=600)

    # Clean up concat list
    try:
        concat_list_path.unlink()
    except OSError:
        pass

    if result.returncode != 0:
        # Fallback: try re-encoding
        print("Stream copy concat failed, trying re-encode fallback...", file=sys.stderr)
        cmd_reencode = [
            'ffmpeg',
            '-f', 'concat',
            '-safe', '0',
            '-i', str(concat_list_path.with_suffix('.txt')),
            '-c:v', 'libx264',
            '-c:a', 'aac',
            '-y',
            output_file
        ]
        # Re-write list for fallback
        with open(concat_list_path, 'w') as f:
            for seg_file in segment_files:
                abs_path = Path(seg_file).resolve()
                f.write(f"file '{abs_path}'\n")

        result2 = subprocess.run(cmd_reencode, capture_output=True, text=True, timeout=600)
        try:
            concat_list_path.unlink()
        except OSError:
            pass

        if result2.returncode != 0:
            return {
                "status": "error",
                "error": "Concat failed with both stream copy and re-encode",
                "stream_copy_stderr": result.stderr,
                "reencode_stderr": result2.stderr,
                "ffmpeg_command": cmd_str
            }

    return {"status": "success", "ffmpeg_command": cmd_str}


def get_video_framerate(filepath: str) -> float:
    """Get the video framerate using ffprobe. Returns 29.97 as fallback."""
    try:
        cmd = [
            'ffprobe', '-v', 'quiet', '-print_format', 'json',
            '-show_streams', '-select_streams', 'v:0', filepath
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        if result.returncode == 0:
            info = json.loads(result.stdout)
            streams = info.get("streams", [])
            if streams:
                r_frame_rate = streams[0].get("r_frame_rate", "30000/1001")
                num, den = r_frame_rate.split("/")
                return float(num) / float(den)
    except Exception:
        pass
    return 29.97


def generate_premiere_xml(clip_files: list, clip_durations: list, sequence_name: str,
                          framerate: float, xml_path: str) -> dict:
    """
    Generate an FCP7 XML file that Premiere Pro can import.
    Places all clips in sequence on a single video+audio track.
    """
    # Round framerate for the XML timebase
    timebase = round(framerate)
    ntsc = "TRUE" if abs(framerate - timebase) > 0.01 else "FALSE"

    def frames(seconds: float) -> int:
        return round(seconds * framerate)

    root = ET.Element("xmeml", version="5")
    sequence = ET.SubElement(root, "sequence")
    ET.SubElement(sequence, "name").text = sequence_name
    ET.SubElement(sequence, "duration").text = str(frames(sum(clip_durations)))

    rate = ET.SubElement(sequence, "rate")
    ET.SubElement(rate, "timebase").text = str(timebase)
    ET.SubElement(rate, "ntsc").text = ntsc

    media = ET.SubElement(sequence, "media")

    # Video track
    video = ET.SubElement(media, "video")
    vtrack = ET.SubElement(video, "track")
    timeline_pos = 0
    for i, (clip_path, dur) in enumerate(zip(clip_files, clip_durations)):
        clip_frames = frames(dur)
        clipitem = ET.SubElement(vtrack, "clipitem", id=f"clip-v-{i+1}")
        ET.SubElement(clipitem, "name").text = Path(clip_path).stem
        ET.SubElement(clipitem, "duration").text = str(clip_frames)
        r = ET.SubElement(clipitem, "rate")
        ET.SubElement(r, "timebase").text = str(timebase)
        ET.SubElement(r, "ntsc").text = ntsc
        ET.SubElement(clipitem, "start").text = str(timeline_pos)
        ET.SubElement(clipitem, "end").text = str(timeline_pos + clip_frames)
        ET.SubElement(clipitem, "in").text = "0"
        ET.SubElement(clipitem, "out").text = str(clip_frames)

        fileref = ET.SubElement(clipitem, "file", id=f"file-{i+1}")
        ET.SubElement(fileref, "name").text = Path(clip_path).name
        ET.SubElement(fileref, "pathurl").text = Path(clip_path).resolve().as_uri()
        fr = ET.SubElement(fileref, "rate")
        ET.SubElement(fr, "timebase").text = str(timebase)
        ET.SubElement(fr, "ntsc").text = ntsc
        ET.SubElement(fileref, "duration").text = str(clip_frames)

        timeline_pos += clip_frames

    # Audio track (mirrors video)
    audio = ET.SubElement(media, "audio")
    atrack = ET.SubElement(audio, "track")
    timeline_pos = 0
    for i, (clip_path, dur) in enumerate(zip(clip_files, clip_durations)):
        clip_frames = frames(dur)
        clipitem = ET.SubElement(atrack, "clipitem", id=f"clip-a-{i+1}")
        ET.SubElement(clipitem, "name").text = Path(clip_path).stem
        ET.SubElement(clipitem, "duration").text = str(clip_frames)
        r = ET.SubElement(clipitem, "rate")
        ET.SubElement(r, "timebase").text = str(timebase)
        ET.SubElement(r, "ntsc").text = ntsc
        ET.SubElement(clipitem, "start").text = str(timeline_pos)
        ET.SubElement(clipitem, "end").text = str(timeline_pos + clip_frames)
        ET.SubElement(clipitem, "in").text = "0"
        ET.SubElement(clipitem, "out").text = str(clip_frames)

        fileref = ET.SubElement(clipitem, "file", id=f"file-{i+1}")

        timeline_pos += clip_frames

    tree = ET.ElementTree(root)
    ET.indent(tree, space="  ")
    Path(xml_path).parent.mkdir(parents=True, exist_ok=True)
    tree.write(xml_path, encoding="utf-8", xml_declaration=True)

    return {"status": "success", "xml_path": str(Path(xml_path).resolve())}


def apply_cuts(cut_spec_path: str, output_file: str, temp_dir: str = "workspace/temp",
               mode: str = "joined", joined_output: str = "") -> dict:
    """
    Main function: extract all keep_segments then output according to mode.

    Modes:
        joined   — concatenate into a single output file (default)
        separate — save each segment as a separate numbered clip
        project  — separate clips + FCP7 XML project file for Premiere Pro
        both     — extract segments once, produce joined file + project clips/XML
                   Requires --joined-output for the joined file path; positional
                   output arg is used as the clips directory (same as project mode).
    """
    t_start = time.time()

    if mode not in ("joined", "separate", "project", "both"):
        return {"status": "error", "error": f"Unknown mode: {mode}. Use joined, separate, project, or both"}

    if mode == "both" and not joined_output:
        return {"status": "error", "error": "--joined-output is required when mode is 'both'"}

    # Load cut spec
    if not Path(cut_spec_path).exists():
        return {"status": "error", "error": f"Cut spec not found: {cut_spec_path}"}

    with open(cut_spec_path) as f:
        spec = json.load(f)

    source = spec.get("source", "")
    keep_segments = spec.get("keep_segments", [])
    removed_segments = spec.get("removed_segments", [])

    # Merge adjacent contiguous segments to avoid tiny fragment clips,
    # then bridge short gaps to preserve brief untranscribed speech.
    original_count = len(keep_segments)
    keep_segments = merge_adjacent_segments(keep_segments)
    keep_segments = bridge_short_gaps(keep_segments)
    if len(keep_segments) < original_count:
        print(f"Merged {original_count} segments → {len(keep_segments)} clips "
              f"(merge + bridge)", file=sys.stderr)

    if not Path(source).exists():
        return {"status": "error", "error": f"Source file not found: {source}"}

    if not keep_segments:
        return {"status": "error", "error": "No keep_segments defined in cut spec"}

    # Calculate total duration of source (for reporting)
    source_duration = 0.0
    try:
        cmd = ['ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_format', source]
        probe = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        if probe.returncode == 0:
            info = json.loads(probe.stdout)
            source_duration = float(info.get("format", {}).get("duration", 0.0))
    except Exception:
        pass

    # Extract each segment to a temp file
    temp_dir = Path(temp_dir)
    temp_dir.mkdir(parents=True, exist_ok=True)
    segment_files = []
    segment_durations = []
    total_kept_duration = 0.0

    # Pre-compute padded timestamps for all segments, then clamp adjacent
    # segments so padding never causes overlapping audio (which would produce
    # doubled words in the output).
    padded = []
    for seg in keep_segments:
        raw_start = parse_timestamp(seg["start"])
        raw_end = parse_timestamp(seg["end"])
        padded.append({
            "raw_start": raw_start,
            "raw_end": raw_end,
            "start": max(0.0, raw_start - START_PADDING_SECONDS),
            "end": raw_end + END_PADDING_SECONDS,
            "note": seg.get("note", ""),
        })

    # Clamp: if segment[i].end (padded) > segment[i+1].start (padded),
    # pull both back to the original unpadded boundary between them.
    for i in range(len(padded) - 1):
        if padded[i]["end"] > padded[i + 1]["start"]:
            boundary = padded[i]["raw_end"]  # == padded[i+1]["raw_start"] for back-to-back
            padded[i]["end"] = boundary
            padded[i + 1]["start"] = boundary

    max_workers = min(6, len(padded))
    print(f"Extracting {len(keep_segments)} segment(s) with {max_workers} parallel workers...", file=sys.stderr)

    def _extract_segment(i: int, seg: dict) -> tuple:
        """Extract a single segment. Returns (index, temp_path, duration, result)."""
        start = seconds_to_hms(seg["start"])
        end = seconds_to_hms(seg["end"])
        note = seg["note"]
        temp_output = str(temp_dir / f"_seg_{i:03d}{Path(source).suffix}")

        print(f"  [{i+1}/{len(keep_segments)}] {start} → {end}  ({note})", file=sys.stderr)

        result = trim_video(source, start, end, temp_output, re_encode=True)
        seg_dur = 0.0
        if result["status"] == "success":
            try:
                seg_dur = parse_timestamp(end) - parse_timestamp(start)
            except ValueError:
                pass
        return (i, temp_output, seg_dur, result)

    # Pre-allocate ordered slots so concat order is preserved
    segment_files = [None] * len(padded)
    segment_durations = [0.0] * len(padded)
    extraction_error = None

    with ThreadPoolExecutor(max_workers=max_workers) as pool:
        futures = {pool.submit(_extract_segment, i, seg): i for i, seg in enumerate(padded)}

        for future in as_completed(futures):
            i, temp_output, seg_dur, result = future.result()
            if result["status"] != "success":
                extraction_error = {
                    "status": "error",
                    "error": f"Failed to extract segment {i+1}: {result.get('error')}",
                    "segment": padded[i],
                    "trim_result": result,
                }
                # Cancel remaining futures
                for f in futures:
                    f.cancel()
                break
            segment_files[i] = temp_output
            segment_durations[i] = seg_dur
            total_kept_duration += seg_dur

    if extraction_error:
        # Clean up any extracted segments
        for f in segment_files:
            if f:
                try:
                    Path(f).unlink()
                except OSError:
                    pass
        return extraction_error

    # --- Mode: joined (default) ---
    if mode == "joined":
        if len(segment_files) == 1:
            Path(output_file).parent.mkdir(parents=True, exist_ok=True)
            shutil.move(segment_files[0], output_file)
            concat_result = {"status": "success", "ffmpeg_command": "single segment — no concat needed"}
        else:
            print(f"Concatenating {len(segment_files)} segments...", file=sys.stderr)
            concat_result = concat_segments(segment_files, output_file, temp_dir)
            for f in segment_files:
                try:
                    Path(f).unlink()
                except OSError:
                    pass

        if concat_result["status"] != "success":
            return concat_result

        output_path = Path(output_file)
        file_size = output_path.stat().st_size if output_path.exists() else 0
        duration_removed = source_duration - total_kept_duration if source_duration > 0 else 0

        elapsed = round(time.time() - t_start, 1)
        print(f"\nDone. Output: {output_file}", file=sys.stderr)
        print(f"  Source duration:   {seconds_to_hms(source_duration)}", file=sys.stderr)
        print(f"  Kept duration:     {seconds_to_hms(total_kept_duration)}", file=sys.stderr)
        print(f"  Removed duration:  {seconds_to_hms(max(0, duration_removed))}", file=sys.stderr)
        print(f"  Segments removed:  {len(removed_segments)}", file=sys.stderr)
        print(f"  Elapsed:           {elapsed}s", file=sys.stderr)

        return {
            "status": "success",
            "mode": "joined",
            "output_file": str(output_path.resolve()),
            "source_file": str(Path(source).resolve()),
            "source_duration_seconds": round(source_duration, 3),
            "output_duration_seconds": round(total_kept_duration, 3),
            "removed_duration_seconds": round(max(0, duration_removed), 3),
            "segments_kept": len(keep_segments),
            "segments_removed": len(removed_segments),
            "file_size_bytes": file_size,
            "file_size_mb": round(file_size / (1024 * 1024), 2),
            "elapsed_seconds": elapsed
        }

    # --- Mode: both (joined + project from a single extraction) ---
    if mode == "both":
        # 1. Concat temp segments into the joined output file
        if len(segment_files) == 1:
            Path(joined_output).parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(segment_files[0], joined_output)
            concat_result = {"status": "success", "ffmpeg_command": "single segment — no concat needed"}
        else:
            print(f"Concatenating {len(segment_files)} segments (joined)...", file=sys.stderr)
            concat_result = concat_segments(segment_files, joined_output, temp_dir)

        if concat_result["status"] != "success":
            for f in segment_files:
                try:
                    Path(f).unlink()
                except OSError:
                    pass
            return concat_result

        joined_path = Path(joined_output)
        joined_size = joined_path.stat().st_size if joined_path.exists() else 0

        # 2. Move temp segments to clips directory + generate XML (project)
        output_dir = Path(output_file)
        output_dir.mkdir(parents=True, exist_ok=True)
        ext = Path(source).suffix

        clip_paths = []
        for i, seg_file in enumerate(segment_files):
            clip_name = f"clip_{i+1:03d}{ext}"
            clip_dest = output_dir / clip_name
            shutil.move(seg_file, str(clip_dest))
            clip_paths.append(str(clip_dest))

        source_stem = Path(source).stem
        xml_path = str(output_dir / f"{source_stem}_project.xml")
        framerate = get_video_framerate(source)
        xml_result = generate_premiere_xml(
            clip_paths, segment_durations, source_stem, framerate, xml_path
        )

        duration_removed = source_duration - total_kept_duration if source_duration > 0 else 0

        elapsed = round(time.time() - t_start, 1)
        print(f"\nDone (both modes). Joined: {joined_output}  |  Clips: {output_dir}", file=sys.stderr)
        print(f"  Source duration:   {seconds_to_hms(source_duration)}", file=sys.stderr)
        print(f"  Kept duration:     {seconds_to_hms(total_kept_duration)}", file=sys.stderr)
        print(f"  Removed duration:  {seconds_to_hms(max(0, duration_removed))}", file=sys.stderr)
        print(f"  Segments removed:  {len(removed_segments)}", file=sys.stderr)
        print(f"  Elapsed:           {elapsed}s", file=sys.stderr)

        result_data = {
            "status": "success",
            "mode": "both",
            "joined": {
                "output_file": str(joined_path.resolve()),
                "file_size_bytes": joined_size,
                "file_size_mb": round(joined_size / (1024 * 1024), 2),
            },
            "project": {
                "output_dir": str(output_dir.resolve()),
                "output_files": [str(Path(p).resolve()) for p in clip_paths],
            },
            "source_file": str(Path(source).resolve()),
            "source_duration_seconds": round(source_duration, 3),
            "output_duration_seconds": round(total_kept_duration, 3),
            "removed_duration_seconds": round(max(0, duration_removed), 3),
            "segments_kept": len(keep_segments),
            "segments_removed": len(removed_segments),
            "elapsed_seconds": elapsed,
        }

        if xml_result["status"] == "success":
            result_data["project"]["xml_file"] = xml_result["xml_path"]
            print(f"  Project XML:       {xml_path}", file=sys.stderr)
        else:
            result_data["project"]["xml_error"] = xml_result.get("error", "Unknown XML generation error")

        return result_data

    # --- Mode: separate / project ---
    # output_file is treated as the output DIRECTORY for these modes
    output_dir = Path(output_file)
    output_dir.mkdir(parents=True, exist_ok=True)
    ext = Path(source).suffix

    clip_paths = []
    for i, seg_file in enumerate(segment_files):
        clip_name = f"clip_{i+1:03d}{ext}"
        clip_dest = output_dir / clip_name
        shutil.move(seg_file, str(clip_dest))
        clip_paths.append(str(clip_dest))

    duration_removed = source_duration - total_kept_duration if source_duration > 0 else 0

    elapsed = round(time.time() - t_start, 1)
    print(f"\nDone. {len(clip_paths)} clip(s) saved to: {output_dir}", file=sys.stderr)
    print(f"  Source duration:   {seconds_to_hms(source_duration)}", file=sys.stderr)
    print(f"  Kept duration:     {seconds_to_hms(total_kept_duration)}", file=sys.stderr)
    print(f"  Removed duration:  {seconds_to_hms(max(0, duration_removed))}", file=sys.stderr)
    print(f"  Segments removed:  {len(removed_segments)}", file=sys.stderr)
    print(f"  Elapsed:           {elapsed}s", file=sys.stderr)

    result_data = {
        "status": "success",
        "mode": mode,
        "output_dir": str(output_dir.resolve()),
        "output_files": [str(Path(p).resolve()) for p in clip_paths],
        "source_file": str(Path(source).resolve()),
        "source_duration_seconds": round(source_duration, 3),
        "output_duration_seconds": round(total_kept_duration, 3),
        "removed_duration_seconds": round(max(0, duration_removed), 3),
        "segments_kept": len(keep_segments),
        "segments_removed": len(removed_segments),
        "elapsed_seconds": elapsed,
    }

    if mode == "project":
        source_stem = Path(source).stem
        xml_path = str(output_dir / f"{source_stem}_project.xml")
        framerate = get_video_framerate(source)
        xml_result = generate_premiere_xml(
            clip_paths, segment_durations, source_stem, framerate, xml_path
        )
        if xml_result["status"] != "success":
            result_data["xml_error"] = xml_result.get("error", "Unknown XML generation error")
        else:
            result_data["xml_file"] = xml_result["xml_path"]
            print(f"  Project XML:       {xml_path}", file=sys.stderr)

    return result_data


def main():
    args = sys.argv[1:]

    if not args or args[0] in ('-h', '--help'):
        print(__doc__)
        sys.exit(0)

    # Parse named options
    temp_dir = "workspace/temp"
    mode = "joined"
    joined_output = ""
    positional = []
    i = 0
    while i < len(args):
        if args[i] == '--temp-dir' and i + 1 < len(args):
            temp_dir = args[i + 1]
            i += 2
        elif args[i] == '--mode' and i + 1 < len(args):
            mode = args[i + 1]
            i += 2
        elif args[i] == '--joined-output' and i + 1 < len(args):
            joined_output = args[i + 1]
            i += 2
        else:
            positional.append(args[i])
            i += 1

    if len(positional) < 2:
        print(json.dumps({
            "status": "error",
            "error": "Usage: apply_cuts.py <cut_spec_json> <output> [--temp-dir <dir>] [--mode <mode>]"
        }, indent=2))
        sys.exit(1)

    cut_spec_path = positional[0]
    output_file = positional[1]

    result = apply_cuts(cut_spec_path, output_file, temp_dir, mode, joined_output)
    print(json.dumps(result, indent=2))
    sys.exit(0 if result['status'] == 'success' else 1)


if __name__ == '__main__':
    main()
